# Form implementation generated from reading ui file 'ui/dbg_send_scintilla_messages.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.message_name = QtWidgets.QLineEdit(parent=Dialog)
        self.message_name.setObjectName("message_name")
        self.horizontalLayout.addWidget(self.message_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.message_args = QtWidgets.QLineEdit(parent=Dialog)
        self.message_args.setObjectName("message_args")
        self.horizontalLayout_2.addWidget(self.message_args)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.sendButton = QtWidgets.QPushButton(parent=Dialog)
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout.addWidget(self.sendButton)
        self.return_label = QtWidgets.QLabel(parent=Dialog)
        self.return_label.setObjectName("return_label")
        self.verticalLayout.addWidget(self.return_label)
        self.label_2.setBuddy(self.message_name)
        self.label_3.setBuddy(self.message_args)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Test Scintilla Messages"))
        self.label_2.setText(_translate("Dialog", "Message: SCI_"))
        self.label_3.setText(_translate("Dialog", "Other arguments:"))
        self.sendButton.setText(_translate("Dialog", "Send"))
        self.return_label.setText(_translate("Dialog", "Return:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
