# Form implementation generated from reading ui file 'ui/make.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_publish_widget(object):
    def setupUi(self, publish_widget):
        publish_widget.setObjectName("publish_widget")
        publish_widget.resize(886, 47)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(publish_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.number_of_docs_label = QtWidgets.QLabel(parent=publish_widget)
        self.number_of_docs_label.setObjectName("number_of_docs_label")
        self.horizontalLayout.addWidget(self.number_of_docs_label)
        self.number_of_docs_spinbox = QtWidgets.QSpinBox(parent=publish_widget)
        self.number_of_docs_spinbox.setAccelerated(True)
        self.number_of_docs_spinbox.setMinimum(1)
        self.number_of_docs_spinbox.setMaximum(1000)
        self.number_of_docs_spinbox.setObjectName("number_of_docs_spinbox")
        self.horizontalLayout.addWidget(self.number_of_docs_spinbox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.generate_docs_button = QtWidgets.QToolButton(parent=publish_widget)
        self.generate_docs_button.setStyleSheet("font-weight: bold;\n"
"margin-left: 10px;")
        self.generate_docs_button.setObjectName("generate_docs_button")
        self.horizontalLayout_2.addWidget(self.generate_docs_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.number_of_docs_label.setBuddy(self.number_of_docs_spinbox)

        self.retranslateUi(publish_widget)
        QtCore.QMetaObject.connectSlotsByName(publish_widget)

    def retranslateUi(self, publish_widget):
        _translate = QtCore.QCoreApplication.translate
        publish_widget.setWindowTitle(_translate("publish_widget", "Generate Documents"))
        self.number_of_docs_label.setText(_translate("publish_widget", "Number of documents: "))
        self.generate_docs_button.setText(_translate("publish_widget", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    publish_widget = QtWidgets.QWidget()
    ui = Ui_publish_widget()
    ui.setupUi(publish_widget)
    publish_widget.show()
    sys.exit(app.exec())
