# Form implementation generated from reading ui file 'ui/find.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(638, 284)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.texts_fields = QtWidgets.QFormLayout()
        self.texts_fields.setObjectName("texts_fields")
        self.findLabel = QtWidgets.QLabel(parent=Dialog)
        self.findLabel.setObjectName("findLabel")
        self.texts_fields.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.findLabel)
        self.findLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.findLineEdit.setObjectName("findLineEdit")
        self.texts_fields.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.findLineEdit)
        self.verticalLayout.addLayout(self.texts_fields)
        self.information_label = QtWidgets.QLabel(parent=Dialog)
        self.information_label.setObjectName("information_label")
        self.verticalLayout.addWidget(self.information_label)
        self.buttons_field = QtWidgets.QHBoxLayout()
        self.buttons_field.setObjectName("buttons_field")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum
        )
        self.buttons_field.addItem(spacerItem)
        self.find_button = QtWidgets.QPushButton(parent=Dialog)
        self.find_button.setObjectName("find_button")
        self.buttons_field.addWidget(self.find_button)
        self.verticalLayout.addLayout(self.buttons_field)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.direction = QtWidgets.QGroupBox(parent=Dialog)
        self.direction.setObjectName("direction")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.direction)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.upRadioButton = QtWidgets.QRadioButton(parent=self.direction)
        self.upRadioButton.setObjectName("upRadioButton")
        self.verticalLayout_3.addWidget(self.upRadioButton)
        self.downRadioButton = QtWidgets.QRadioButton(parent=self.direction)
        self.downRadioButton.setChecked(True)
        self.downRadioButton.setObjectName("downRadioButton")
        self.verticalLayout_3.addWidget(self.downRadioButton)
        self.verticalLayout_2.addWidget(self.direction)
        self.options = QtWidgets.QGroupBox(parent=Dialog)
        self.options.setObjectName("options")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.options)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.caseCheckBox = QtWidgets.QCheckBox(parent=self.options)
        self.caseCheckBox.setObjectName("caseCheckBox")
        self.verticalLayout_4.addWidget(self.caseCheckBox)
        self.wholeCheckBox = QtWidgets.QCheckBox(parent=self.options)
        self.wholeCheckBox.setObjectName("wholeCheckBox")
        self.verticalLayout_4.addWidget(self.wholeCheckBox)
        self.regexCheckBox = QtWidgets.QCheckBox(parent=self.options)
        self.regexCheckBox.setObjectName("regexCheckBox")
        self.verticalLayout_4.addWidget(self.regexCheckBox)
        self.checkBox = QtWidgets.QCheckBox(parent=self.options)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.verticalLayout_2.addWidget(self.options)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.findLabel.setBuddy(self.findLineEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.findLineEdit, self.upRadioButton)
        Dialog.setTabOrder(self.upRadioButton, self.downRadioButton)
        Dialog.setTabOrder(self.downRadioButton, self.caseCheckBox)
        Dialog.setTabOrder(self.caseCheckBox, self.wholeCheckBox)
        Dialog.setTabOrder(self.wholeCheckBox, self.regexCheckBox)
        Dialog.setTabOrder(self.regexCheckBox, self.checkBox)
        Dialog.setTabOrder(self.checkBox, self.find_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Find"))
        self.findLabel.setText(_translate("Dialog", "Fi&nd"))
        self.information_label.setText(_translate("Dialog", "Information"))
        self.find_button.setText(_translate("Dialog", "&Find"))
        self.direction.setTitle(_translate("Dialog", "D&irection"))
        self.upRadioButton.setText(_translate("Dialog", "&Up"))
        self.downRadioButton.setText(_translate("Dialog", "&Down"))
        self.options.setTitle(_translate("Dialog", "&Options"))
        self.caseCheckBox.setText(_translate("Dialog", "&Case sensitive"))
        self.wholeCheckBox.setText(_translate("Dialog", "&Whole words only"))
        self.regexCheckBox.setToolTip(
            _translate(
                "Dialog",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Sans'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">whether the text to search should be interpreted as a regular expression.</p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">You may want to take a look at the syntax of regular expressions:</p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="http://doc.trolltech.com/qregexp.html"><span style=" text-decoration: underline; color:#0000ff;">http://doc.trolltech.com/qregexp.html</span></a></p></body></html>',
            )
        )
        self.regexCheckBox.setText(_translate("Dialog", "R&egular Expression"))
        self.checkBox.setText(_translate("Dialog", "&Selection only"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
